[bluetooth]
enabled=true
continuous_advertising=true
service_uuid=30470000-ad05-4000-8000-000000000001

[wifi]
enabled=true
ssid_prefix=_ADOS-DISP-
hidden=true
subnet=10.77.0.0/30
host_address=10.77.0.1
client_address=10.77.0.2

[apdp]
tcp_port=3047
require_session_auth=true
